"""Membro 2 — Locais, itens por local e criaturas do MVP."""

ITENS_POR_LOCAL = {
    "Vila das Preguiças": [
        {
            "nome": "Poção Pequena de HP",
            "tipo": "consumivel",
            "raridade": "comum",
            "peso": 1,
            "valor_magico": 5,
            "preco": 15,
            "efeitos": {"hp": 30},
            "descricao": "Restaura 30 pontos de HP.",
        },
        {
            "nome": "Algodão Macio",
            "tipo": "material",
            "raridade": "comum",
            "peso": 1,
            "valor_magico": 3,
            "preco": 5,
            "efeitos": {},
            "descricao": "Fibra leve usada por Camila para criar capas e mantos.",
        },
    ],
    "Lago das Capivaras": [
        {
            "nome": "Anel de Vitória-régia",
            "tipo": "equipamento",
            "slot": "anel",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 35,
            "preco": 80,
            "efeitos": {"hp_max": 20},
            "descricao": "+20 de HP máximo.",
        },
        {
            "nome": "Concha Rosada da Beatriz",
            "tipo": "material",
            "raridade": "incomum",
            "peso": 1,
            "valor_magico": 12,
            "preco": 18,
            "efeitos": {},
            "descricao": "Uma concha rosada encontrada perto da margem onde Beatriz costuma aparecer.",
        },

        {
            "nome": "Poção de Mana",
            "tipo": "consumivel",
            "raridade": "comum",
            "peso": 1,
            "valor_magico": 8,
            "preco": 18,
            "efeitos": {"mana": 25},
            "descricao": "Restaura 25 pontos de mana.",
        },
    ],
    "Bosque do Ipê": [
        {
            "nome": "Flor de Ipê",
            "tipo": "missao",
            "raridade": "comum",
            "peso": 1,
            "valor_magico": 12,
            "preco": 10,
            "efeitos": {},
            "descricao": "Flor usada por Camila para acalmar as formigas luminosas.",
        },
        {
            "nome": "Algodão Macio",
            "tipo": "material",
            "raridade": "comum",
            "peso": 1,
            "valor_magico": 3,
            "preco": 5,
            "efeitos": {},
            "descricao": "Algodão recolhido entre as raízes do Bosque do Ipê.",
        },
        {
            "nome": "Capa de Ipê Roxo",
            "tipo": "equipamento",
            "slot": "capa",
            "raridade": "rara",
            "peso": 2,
            "valor_magico": 40,
            "preco": 90,
            "efeitos": {"magia": 3},
            "descricao": "+3 de magia.",
        },
        {
            "nome": "Fragmento de Seiva",
            "tipo": "missao",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 50,
            "preco": 0,
            "efeitos": {},
            "descricao": "Fragmento necessário para restaurar a Árvore do Mundo.",
        },
    ],
    "Ruínas da Arpia": [
        {
            "nome": "Staff de Brasa",
            "tipo": "equipamento",
            "slot": "arma",
            "raridade": "epica",
            "peso": 3,
            "valor_magico": 70,
            "preco": 120,
            "efeitos": {"magia": 4, "fire": 1},
            "descricao": "+4 magia e +1 bônus de fire.",
        },
        {
            "nome": "Orbe de Geada",
            "tipo": "equipamento",
            "slot": "amuleto",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 55,
            "preco": 95,
            "efeitos": {"magia": 2, "blizzard": 1},
            "descricao": "+2 magia e +1 bônus de Blizzard.",
        },
        {
            "nome": "Dólar Místico",
            "tipo": "equipamento",
            "slot": "amuleto",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 60,
            "preco": 100,
            "efeitos": {"mana_max": 50},
            "descricao": "+50 de mana máxima.",
        },
        {
            "nome": "Cajado das Marés",
            "tipo": "equipamento",
            "slot": "arma",
            "raridade": "rara",
            "peso": 2,
            "valor_magico": 62,
            "preco": 105,
            "efeitos": {"magia": 2, "water": 1},
            "descricao": "+2 magia e +1 bônus de Water.",
        },
        {
            "nome": "Cristal Sombrio",
            "tipo": "equipamento",
            "slot": "amuleto",
            "raridade": "epica",
            "peso": 1,
            "valor_magico": 72,
            "preco": 130,
            "efeitos": {"dark": 1, "mana_max": 20},
            "descricao": "+1 bônus de Dark e +20 mana máxima.",
        },
    ],
    "Caverna dos Golems": [
        {
            "nome": "Adagas de Veneno",
            "tipo": "equipamento",
            "slot": "arma",
            "raridade": "epica",
            "peso": 2,
            "valor_magico": 65,
            "preco": 110,
            "efeitos": {"ataque": 2, "veneno": 10},
            "descricao": "+2 ataque e +10 veneno.",
        },
        {
            "nome": "Bracelete de Trovão",
            "tipo": "equipamento",
            "slot": "anel",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 58,
            "preco": 105,
            "efeitos": {"thunder": 1, "mana_max": 15},
            "descricao": "+1 bônus de thunder e +15 mana máxima.",
        },
        {
            "nome": "Totem de Barro do Mitis",
            "tipo": "equipamento",
            "slot": "amuleto",
            "raridade": "rara",
            "peso": 1,
            "valor_magico": 52,
            "preco": 95,
            "efeitos": {"quake": 2},
            "descricao": "+2 bônus de Quake para Mitis.",
        },
        {
            "nome": "Fragmento de Seiva Profunda",
            "tipo": "missao",
            "raridade": "epica",
            "peso": 1,
            "valor_magico": 80,
            "preco": 0,
            "efeitos": {},
            "descricao": "Fragmento forte da raiz da Árvore do Mundo.",
        },
    ],
    "Clareira da Árvore do Mundo": [
        {
            "nome": "Flor da Seiva Clara",
            "tipo": "missao",
            "raridade": "lendaria",
            "peso": 1,
            "valor_magico": 100,
            "preco": 0,
            "efeitos": {},
            "descricao": "Item final para estabilizar a magia da floresta.",
        }
    ],
}


# Itens extras adicionados para aumentar a variedade de coleta, loja e crafting.
ITENS_POR_LOCAL["Vila das Preguiças"].extend([
    {
        "nome": "Folha de Guaraná",
        "tipo": "material",
        "raridade": "comum",
        "peso": 1,
        "valor_magico": 6,
        "preco": 8,
        "efeitos": {},
        "descricao": "Folha usada em receitas de recuperação e chás energéticos.",
    },
    {
        "nome": "Pedra Fluorescente Pequena",
        "tipo": "material",
        "raridade": "incomum",
        "peso": 1,
        "valor_magico": 15,
        "preco": 18,
        "efeitos": {},
        "descricao": "Pedra que brilha no escuro e reage à magia da Árvore do Mundo.",
    },
])

ITENS_POR_LOCAL["Lago das Capivaras"].extend([
    {
        "nome": "Semente de Guaraná",
        "tipo": "consumivel",
        "raridade": "incomum",
        "peso": 1,
        "valor_magico": 18,
        "preco": 35,
        "efeitos": {"regen_hp": 10, "regen_mana": 5, "duracao_turnos": 4},
        "descricao": "Regenera 10 HP e 5 mana por turno durante 4 turnos (12s narrativos).",
    },
    {
        "nome": "Anel de Guaraná",
        "tipo": "equipamento",
        "slot": "anel",
        "raridade": "incomum",
        "peso": 1,
        "valor_magico": 28,
        "preco": 65,
        "efeitos": {"hp_max": 10, "mana_max": 10},
        "descricao": "+10 HP máximo e +10 mana máxima.",
    },
])

ITENS_POR_LOCAL["Bosque do Ipê"].extend([
    {
        "nome": "Flor Azul de Mana",
        "tipo": "material",
        "raridade": "incomum",
        "peso": 1,
        "valor_magico": 20,
        "preco": 20,
        "efeitos": {},
        "descricao": "Flor usada em receitas mágicas e encantamentos de mana.",
    },
    {
        "nome": "Folha de Ipê Dourada",
        "tipo": "material",
        "raridade": "rara",
        "peso": 1,
        "valor_magico": 24,
        "preco": 25,
        "efeitos": {},
        "descricao": "Folha rara que guarda energia solar.",
    },
])

ITENS_POR_LOCAL["Ruínas da Arpia"].extend([
    {
        "nome": "Amuleto de Pedra Fluorescente",
        "tipo": "equipamento",
        "slot": "amuleto",
        "raridade": "rara",
        "peso": 1,
        "valor_magico": 48,
        "preco": 90,
        "efeitos": {"magia": 1, "mana_max": 20},
        "descricao": "+1 magia e +20 mana máxima.",
    },
    {
        "nome": "Anel das Folhas Claras",
        "tipo": "equipamento",
        "slot": "anel",
        "raridade": "incomum",
        "peso": 1,
        "valor_magico": 32,
        "preco": 70,
        "efeitos": {"defesa": 1, "cure": 1},
        "descricao": "+1 defesa e +1 bônus de Cure.",
    },
])

ITENS_POR_LOCAL["Caverna dos Golems"].extend([
    {
        "nome": "Pedra Fluorescente Grande",
        "tipo": "material",
        "raridade": "rara",
        "peso": 2,
        "valor_magico": 35,
        "preco": 45,
        "efeitos": {},
        "descricao": "Cristal de caverna usado para equipamentos de defesa e magia.",
    },
    {
        "nome": "Amuleto da Raiz Profunda",
        "tipo": "equipamento",
        "slot": "amuleto",
        "raridade": "epica",
        "peso": 1,
        "valor_magico": 75,
        "preco": 135,
        "efeitos": {"defesa": 2, "quake": 1},
        "descricao": "+2 defesa e +1 bônus de Quake.",
    },
])

ITENS_POR_LOCAL["Clareira da Árvore do Mundo"].extend([
    {
        "nome": "Flor Estelar da Clareira",
        "tipo": "material",
        "raridade": "lendaria",
        "peso": 1,
        "valor_magico": 90,
        "preco": 0,
        "efeitos": {},
        "descricao": "Flor luminosa que só aparece perto da Árvore do Mundo.",
    },
])

CRIATURAS_POR_LOCAL = {
    "Lago das Capivaras": {
        "nome": "Lodo Saltitante",
        "hp": 35,
        "ataque": 6,
        "defesa": 2,
        "exp": 25,
        "moedas": 20,
        "fraquezas": ["thunder"],
        "resistencias": ["blizzard"],
        "tipo_dano": "fisico",
    },
    "Bosque do Ipê": {
        "nome": "Galho Corrompido",
        "hp": 45,
        "ataque": 8,
        "defesa": 3,
        "exp": 35,
        "moedas": 28,
        "fraquezas": ["fire"],
        "resistencias": ["quake"],
        "tipo_dano": "fisico",
    },
    "Ruínas da Arpia": {
        "nome": "Pena Sombria",
        "hp": 55,
        "ataque": 10,
        "defesa": 4,
        "exp": 45,
        "moedas": 38,
        "fraquezas": ["blizzard"],
        "resistencias": ["fire", "dark"],
        "tipo_dano": "magico",
    },
    "Caverna dos Golems": {
        "nome": "Golem de Seiva",
        "hp": 75,
        "ataque": 12,
        "defesa": 6,
        "exp": 70,
        "moedas": 55,
        "fraquezas": ["blizzard", "water", "quake"],
        "resistencias": ["thunder", "dark"],
        "tipo_dano": "fisico",
        "aplica_veneno": True,
    },
}
